"""

Revision ID: 95fe341db985
Revises: 
Create Date: 2025-08-05 18:13:40.487597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fe341db985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cranes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('chassis_type', sa.String(), nullable=False),
    sa.Column('pricebook', sa.String(), nullable=False),
    sa.Column('resource_code', sa.String(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('max_lifting_capacity', sa.Float(), nullable=False),
    sa.Column('lc_table_radiuses', sa.JSON(), nullable=False),
    sa.Column('lc_table', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'model', name='uq_manufacturer_model')
    )
    op.create_table('crane_binary_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crane_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['crane_id'], ['cranes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crane_binary_attachments')
    op.drop_table('cranes')
    # ### end Alembic commands ###
